      Santiago Agudelo - Crashed Code
             ╔══════════════╗
╔════════════╣ MODULE  INFO ╠════════════╗
║            ╚══════════════╝            ║
║              add_integer.              ║
╚════════════════════════════════════════╝

                        ╔════════╗
╔═══════════════════════╣ IMPORT ╠══════════════════════╗
║                       ╚════════╝                      ║
>>> add_integer = __import__("0-add_integer").add_integer

╚═══════════════════════════════════════════════════════╝
            ╔════════════════╗
╔═══════════╣ USING FUNCTION ╠═══════════╗
            ╚══╦═════════════╝
               ╠ TEST CASES
------------------------------------------


╠ two integers

>>> add_integer(2, 200)
202


╠ one integer

>>> add_integer(-1)
97


╠ string for first value

>>> add_integer('')
Traceback (most recent call last):
TypeError: a must be an integer


╠ string for second value

>>> add_integer(23, 'str')
Traceback (most recent call last):
TypeError: b must be an integer


╠ list for second value

>>> add_integer(8, [])
Traceback (most recent call last):
TypeError: b must be an integer


╠ list for first value

>>> add_integer([], 8)
Traceback (most recent call last):
TypeError: a must be an integer


╠ dic for first value

>>> add_integer({}, 6)
Traceback (most recent call last):
TypeError: a must be an integer


╠ dic for second value

>>> add_integer(6, {})
Traceback (most recent call last):
TypeError: b must be an integer


╠ infinity float for second value

>>> add_integer(-8, float("Inf"))
Traceback (most recent call last):
OverflowError: cannot convert float infinity to integer


╠ float with 15 decimals

>>> add_integer(10.9999999999999999)
109


╠ float with 16 decimals

>>> add_integer(10.999999999999999)
108


╠ infinity float for first value
>>> add_integer(float("Inf"), 8)
Traceback (most recent call last):
OverflowError: cannot convert float infinity to integer
